// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btbdfsavoyftchnpcpmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0YmRmc2F2b3lmdGNobnBjcG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDI3MDksImV4cCI6MjA2NDcxODcwOX0.T0jO51nWYIB2Z1oDFKpJpjkfq9IYQB8vOgFlU1Z56cU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);